apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencart
  namespace: opencart

spec:
# Will have to change
  project: opencart

  source:
  #Will have to change
    chart: opencart
    helm:
      values: |
        service:
          type: ClusterIP
          ports:
            http: 81
            https: 444
        ingress:
          enabled: true
        mariadb:
          auth:
            rootpassword: "12"
            password: "13"
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.2.5
  destination:
    server: https://kubernetes.default.svc
    #change to opencart?
    namespace: opencart

  syncPolicy:
  # uncomment to create namespace if not present
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
