apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencart-argo
  namespace: default

spec:
# Will have to change
  project: default

  source:
  #Will have to change
    repoURL: https://charts.bitnami.com/bitnami/opencart
    targetRevision: 12.5.5
  destination:
    server: https://kubernetes.default.svc
    #change to opencart?
    namespace: default

  syncPolicy:
  # uncomment to create namespace if not present
#    syncOptions:
#    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
